name: Build & Deploy to Oracle Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # üëá THIS is the key line you asked for
    runs-on: [ self-hosted, Linux, ARM64]


    steps:
      # 1Ô∏è‚É£ Pull code onto the Oracle VM
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Build image directly in containerd (Kubernetes runtime)
      - name: Build image in Kubernetes runtime
        run: |
          sudo nerdctl -n k8s.io build -t test-app-ci-cd:latest .

      # 3Ô∏è‚É£ (Optional) Show cluster connection
      - name: Verify Kubernetes access
        run: |
          kubectl get nodes

      # 4Ô∏è‚É£ Deploy to Kubernetes
      - name: Deploy application
        run: |
          kubectl apply -f k8s/
